/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package deliveryoversightsystem.systemAdmin;

import com.toedter.calendar.JDateChooser;
import connection.AccessLayer;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.UpdateUserAccountModel;
import view.OptionPane;

/**
 *
 * @author Aimee
 */
public class EditUserAccount extends javax.swing.JFrame {

    public static EditUserAccount instance; //this might be thecause of the issue
    private static String empID;
    
    public static void setInstance(EditUserAccount aInstance) { //this might be thecause of the issue
      instance = aInstance;
    }
    
    /**
     * Creates new form EditUserAccount
     * @param empID
     */
    public EditUserAccount(String empID) {
        this.empID = empID;
        initComponents();
        instance = this; //this might be thecause of the issue
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
    }

    public static EditUserAccount getInstance(String empID){ //this might be thecause of the issue
        if(instance == null)
            instance = new EditUserAccount(empID);
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dosLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        createUserAcctLabel = new javax.swing.JLabel();
        empIDLabel = new javax.swing.JLabel();
        empIDField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        basicInformationLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        firstnameLabel = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        bdateLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        positionField = new javax.swing.JComboBox();
        createBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        resetBtn = new javax.swing.JButton();
        bdateField = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        dosLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dosLabel.setForeground(new java.awt.Color(255, 255, 255));
        dosLabel.setText("Delivery Oversight System");

        createUserAcctLabel.setBackground(new java.awt.Color(255, 255, 255));
        createUserAcctLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        createUserAcctLabel.setForeground(new java.awt.Color(255, 255, 255));
        createUserAcctLabel.setText("( Edit User Account )");

        empIDLabel.setBackground(new java.awt.Color(255, 255, 255));
        empIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        empIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        empIDLabel.setText("Employee ID");

        empIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDFieldActionPerformed(evt);
            }
        });

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        basicInformationLabel.setBackground(new java.awt.Color(0, 153, 204));
        basicInformationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        basicInformationLabel.setForeground(new java.awt.Color(255, 255, 255));
        basicInformationLabel.setText("Basic Information");

        lastnameLabel.setBackground(new java.awt.Color(255, 255, 255));
        lastnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnameLabel.setText("Lastname");

        firstnameLabel.setBackground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        firstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setText("Firstname");

        bdateLabel.setBackground(new java.awt.Color(255, 255, 255));
        bdateLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        bdateLabel.setForeground(new java.awt.Color(255, 255, 255));
        bdateLabel.setText("Birthday");

        positionLabel.setBackground(new java.awt.Color(255, 255, 255));
        positionLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(255, 255, 255));
        positionLabel.setText("Position");

        positionField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Warehouse Manager", "Purchasing Head", "System Admin" }));
        positionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionFieldActionPerformed(evt);
            }
        });

        createBtn.setBackground(new java.awt.Color(255, 255, 255));
        createBtn.setForeground(new java.awt.Color(0, 153, 255));
        createBtn.setText("UPDATE");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(255, 255, 255));
        resetBtn.setForeground(new java.awt.Color(255, 0, 102));
        resetBtn.setText("CANCEL");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        bdateField.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(createUserAcctLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(empIDLabel)
                        .addGap(18, 18, 18)
                        .addComponent(empIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(passwordLabel)
                        .addGap(18, 18, 18)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dosLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(basicInformationLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bdateLabel)
                                    .addComponent(lastnameLabel))
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(bdateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnameLabel)
                                    .addComponent(positionLabel))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createUserAcctLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDLabel)
                    .addComponent(empIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameLabel)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdateLabel)
                            .addComponent(positionLabel)
                            .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createBtn)
                            .addComponent(resetBtn))
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_empIDFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void positionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String employeeID = getEmpIDField().getText().trim();
        String emPword = getPasswordField().getText().trim();
        String lastName = getLastnameField().getText().trim();
        String firstName = getFirstnameField().getText().trim();
      
        
        if(employeeID.isEmpty() || emPword.isEmpty() || lastName.isEmpty() || firstName.isEmpty()){
                    OptionPane.error("There is an empty required filed. Please fill it up.");
                        return;
        } 
        
        if(new UpdateUserAccountModel(employeeID, firstName, lastName, emPword).updateUserAccount())
                //clearAddDependentsPanel();
                    //updateDependentTable(Dependent.getAllDependents());
        System.gc();


    }//GEN-LAST:event_createBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:

//        int choice = OptionPane.confirmationDialog("Are you sure you want to reset?");
//        if(choice == JOptionPane.YES_OPTION){
//            clearCreateUserFields();
//        }
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserAccount(empID).setVisible(true);
            }
        });
    }
    
    public void setEnabled(){
        getEmpIDField().setText(empID); //for temporary purpose
        getEmpIDField().setEnabled(false);
        getBdateField().setEnabled(false);
        getPositionField().setEnabled(false);
        
    }
    
    private String m_empID, m_lastName, m_firstName, m_birthDate, m_userPos;
    private int m_userType;
    
    public void setEditForm(String empID){
        ResultSet eID = AccessLayer.getInstance().getPassword(empID);
        ResultSet LName = AccessLayer.getInstance().getLastname(empID);
        ResultSet FName = AccessLayer.getInstance().getFirstname(empID);
        ResultSet bDate = AccessLayer.getInstance().getBdate(empID);
        ResultSet ePos = AccessLayer.getInstance().getPosition(empID);
        
        if(eID == null)
            return;
        
        try{
            eID.next();
            LName.next();
            FName.next();
            bDate.next();
            ePos.next();
            
            m_empID = eID.getString(1);
            m_lastName = LName.getString(1);
            m_firstName = FName.getString(1);
            m_birthDate = bDate.getString(1);
            m_userPos = ePos.getString(1);
            
            if(m_userPos.equalsIgnoreCase("PH")){
                m_userType = 0;
            }else if(m_userPos.equalsIgnoreCase("WM")){
                m_userType = 1;
            }else{ // for SA userType
                m_userType = 2;
            }
            
        }catch (SQLException ex) {}
            getPasswordField().setText(m_empID);
            getLastnameField().setText(m_lastName);
            getFirstnameField().setText(m_firstName);
            
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            
            try{
                getBdateField().setDate(format.parse(m_birthDate));
                
            }catch (ParseException ex) {
                Logger.getLogger(EditUserAccount.class.getName()).log(Level.SEVERE, null, ex);
                AccessLayer.getInstance().addToERRORLog(ex.getLocalizedMessage());
            }
            
            getPositionField().setSelectedIndex(m_userType);
    }
    
    /**Getters and Setters**/
    public JDateChooser getBdateField() {
        return bdateField;
    }

    public void setBdateField(JDateChooser bdateField) {
        this.bdateField = bdateField;
    }

    public JTextField getEmpIDField() {
        return empIDField;
    }

    public void setEmpIDField(JTextField empIDField) {
        this.empIDField = empIDField;
    }

    public JTextField getFirstnameField() {
        return firstnameField;
    }

    public void setFirstnameField(JTextField firstnameField) {
        this.firstnameField = firstnameField;
    }

    public JTextField getLastnameField() {
        return lastnameField;
    }

    public void setLastnameField(JTextField lastnameField) {
        this.lastnameField = lastnameField;
    }

    public JTextField getPasswordField() {
        return passwordField;
    }

    public void setPasswordField(JTextField passwordField) {
        this.passwordField = passwordField;
    }

    public JComboBox getPositionField() {
        return positionField;
    }

    public void setPositionField(JComboBox positionField) {
        this.positionField = positionField;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basicInformationLabel;
    private com.toedter.calendar.JDateChooser bdateField;
    private javax.swing.JLabel bdateLabel;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel createUserAcctLabel;
    private javax.swing.JLabel dosLabel;
    private javax.swing.JTextField empIDField;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox positionField;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
