/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package deliveryoversightsystem.purchasingHd;

import connection.AccessLayer;
import deliveryoversightsystem.loginModule;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.addItemModel;
import model.newItemsModel;
import model.responseListModel;
import model.updatesModel;
import view.OptionPane;

/**
 *
 * @author Aimee
 */
public class purchaseHeadHome extends javax.swing.JFrame {

    
    public static purchaseHeadHome instance;
    
    public static void setInstance(purchaseHeadHome aInstance) {
      instance = aInstance;
    }
    
    /**
     * Creates new form purchaseHeadHome
     */
    public purchaseHeadHome() {
        initComponents();
        instance = this;
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
    }
    
    public static purchaseHeadHome getInstance(){
        if(instance == null)
            instance = new purchaseHeadHome();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dosLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        homePHLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseHeadHomeTable = new javax.swing.JTable();
        viewUpdatesBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        purchaseHeadHomeCB = new javax.swing.JComboBox();
        purchaseHeadHomeSearchField = new javax.swing.JTextField();
        goBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        viewResponsesBtn = new javax.swing.JButton();
        followUpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(764, 450));

        dosLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dosLabel.setForeground(new java.awt.Color(255, 255, 255));
        dosLabel.setText("Delivery Oversight System");

        homePHLabel.setBackground(new java.awt.Color(255, 255, 255));
        homePHLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        homePHLabel.setForeground(new java.awt.Color(255, 255, 255));
        homePHLabel.setText("HOME ( Purchasing Head )");

        purchaseHeadHomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Purchaser", "Purchase Order No.", "Supplier Name", "Date Faxed", "Delivery Status", "Follow-Up?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        purchaseHeadHomeTable.setGridColor(new java.awt.Color(0, 153, 204));
        purchaseHeadHomeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseHeadHomeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(purchaseHeadHomeTable);

        viewUpdatesBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewUpdatesBtn.setForeground(new java.awt.Color(0, 153, 255));
        viewUpdatesBtn.setText("View Updates");
        viewUpdatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpdatesBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(255, 255, 255));
        refreshBtn.setForeground(new java.awt.Color(0, 153, 255));
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshBtn.png"))); // NOI18N
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnjButton1ActionPerformed(evt);
            }
        });

        purchaseHeadHomeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        goBtn.setBackground(new java.awt.Color(255, 255, 255));
        goBtn.setForeground(new java.awt.Color(0, 153, 255));
        goBtn.setText("GO");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnjButton1ActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setForeground(new java.awt.Color(0, 153, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-25.png"))); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        viewResponsesBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewResponsesBtn.setForeground(new java.awt.Color(0, 153, 255));
        viewResponsesBtn.setText("View Responses");
        viewResponsesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResponsesBtnActionPerformed(evt);
            }
        });

        followUpBtn.setBackground(new java.awt.Color(255, 255, 255));
        followUpBtn.setForeground(new java.awt.Color(0, 153, 255));
        followUpBtn.setText("Follow-Up Delivery");
        followUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(purchaseHeadHomeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purchaseHeadHomeSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewResponsesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewUpdatesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dosLabel)
                            .addComponent(homePHLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(followUpBtn)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homePHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseHeadHomeCB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewUpdatesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseHeadHomeSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(viewResponsesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(followUpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnjButton1ActionPerformed
        // TODO add your handling code here:
        updateViewPHTable(newItemsModel.getAllNewItems()); //added by angela 12/30/16
    }//GEN-LAST:event_refreshBtnjButton1ActionPerformed

    private void goBtnjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goBtnjButton1ActionPerformed

    private purchaseHeadHome PH;
    //private loginModule LM;
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        
        int choice = OptionPane.confirmationDialog("Are you sure you want to logout?");
        if(choice == JOptionPane.YES_OPTION){
            setVisible(false);
            loginModule.instance.logout();
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private ViewUpdatesForPH PHUpdatesBtn;
    private void viewUpdatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpdatesBtnActionPerformed
        // TODO add your handling code here:
        PHUpdatesBtn = new ViewUpdatesForPH();
        PHUpdatesBtn.setVisible(true);
        purchaseHeadHome.instance.setEnabled(false);
        
        //PHUpdatesBtn.updateViewUpdatesTable(addItemModel.getAllInvoice());
        PHUpdatesBtn.updateViewUpdatesTable(updatesModel.getAllUpdates());
        
        System.gc();
    }//GEN-LAST:event_viewUpdatesBtnActionPerformed

    private AnsweredFollowUpList AF;
    
    private void viewResponsesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResponsesBtnActionPerformed
        // TODO add your handling code here:
        AF = new AnsweredFollowUpList();
        AF.setVisible(true);
        purchaseHeadHome.instance.setEnabled(false);
        
        AF.updateViewResponsesTable(responseListModel.getAllResponses());
        
        System.gc();
    }//GEN-LAST:event_viewResponsesBtnActionPerformed

    private void followUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUpBtnActionPerformed
        // TODO add your handling code here:
        // Sets the followUpFlag to 1; meaning it needs follow-up
        // Created by Angela
        
        String followUpState = "";
        String currDate = "";
        
        ResultSet rs = AccessLayer.getInstance().getFlag(purchaseNoID);
        
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            currDate = dateFormat.format(date);
            
        }catch(Exception e){
            OptionPane.error("Error! Invalid.");
        }
        
        try{
            rs.next();
            followUpState = rs.getString(1);
        }catch (SQLException ex) {}
        
        if(followUpState.equalsIgnoreCase("DONE")){ //follow-up has been done already
            JOptionPane.showMessageDialog(null,"Follow-up for this item has already been done. One follow-up per day only.");
            
        }else if(followUpState.equalsIgnoreCase(" ")){ //follow-up has not yet been done
            int choice = OptionPane.confirmationDialog("Are you sure you want to follow-up this delivery?");
            
            if(choice == JOptionPane.YES_OPTION){
                AccessLayer.getInstance().followUpItem(purchaseNoID, currDate);
                updateViewPHTable(newItemsModel.getAllNewItems()); //to refresh table after adding a follow-up
            }
            
        }
        
    }//GEN-LAST:event_followUpBtnActionPerformed

    public String purchaseNoID;
    
    private void purchaseHeadHomeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseHeadHomeTableMouseClicked
        // TODO add your handling code here:
        int i = evt.getY()/getPurchaseHeadHomeTable().getRowHeight();
        if(evt.getClickCount() == 2 && i < getPurchaseHeadHomeTable().getRowCount()){
            //setUpdateDependentOK(true);
            //setUpdateEmployeePanelValues(getDependentFromTable(i));
            purchaseNoID = getPurchaseOrderNo(i);
            System.gc();
        }
    }//GEN-LAST:event_purchaseHeadHomeTableMouseClicked

    /**
     * get the data from the table at row i
     * @param i row
     * @return a String from row i
     */
    private String getPurchaseOrderNo(int i){
        String purchaseNo = getPurchaseHeadHomeTable().getValueAt(i, 0).toString();
        return purchaseNo;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchaseHeadHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchaseHeadHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchaseHeadHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchaseHeadHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchaseHeadHome().setVisible(true);
            }
        });
    }
    
    private void showExitDialog(){
            purchaseHeadHome.instance.setEnabled(true);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt){
        showExitDialog();
    }

    public JTable getPurchaseHeadHomeTable() {
        return purchaseHeadHomeTable;
    }

    public void setPurchaseHeadHomeTable(JTable purchaseHeadHomeTable) {
        this.purchaseHeadHomeTable = purchaseHeadHomeTable;
    }
    
     /**
     * added by angela 12/30/16
     * @param newList 
     */
    public void updateViewPHTable(ArrayList<newItemsModel> newList){ 
        
        //JOptionPane.showMessageDialog(null,"Getting table results...");
        if(newList == null)
            return;
        DefaultTableModel model = (DefaultTableModel) getPurchaseHeadHomeTable().getModel();
        int size = newList.size(), modelRows = model.getRowCount();
        if(size > modelRows){
            for(int i = size-modelRows; i > 0; i--)
                model.addRow(new String[model.getColumnCount()]);
        }
        else if(modelRows > size){
            for(int i = modelRows-size; i > 0; i--)
                model.removeRow(0);
        }
        for(int i = 0; i < newList.size(); i++){
            newItemsModel m = newList.get(i);
            
            model.setValueAt(m.getPurchaseNo(),i,0);
            model.setValueAt(m.getPurchaserName(),i,1);
            model.setValueAt(m.getSuppName(),i,2);
            model.setValueAt(m.getFaxedDate(),i,3);
            model.setValueAt(m.getDeliveryStat(),i,4);
            model.setValueAt(m.getFollowUpFlag(),i,5);
            
        }
        System.gc();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dosLabel;
    private javax.swing.JButton followUpBtn;
    private javax.swing.JButton goBtn;
    private javax.swing.JLabel homePHLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JComboBox purchaseHeadHomeCB;
    private javax.swing.JTextField purchaseHeadHomeSearchField;
    private javax.swing.JTable purchaseHeadHomeTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton viewResponsesBtn;
    private javax.swing.JButton viewUpdatesBtn;
    // End of variables declaration//GEN-END:variables
}
