/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package deliveryoversightsystem.warehouseMgr;

import connection.AccessLayer;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.responseModel;
import view.OptionPane;

/**
 *
 * @author Aimee
 */
public class RespondToFollowUp_WM extends javax.swing.JFrame {

    public static RespondToFollowUp_WM instance;
    public static String purchaseNoID;
    
    public static void setInstance(RespondToFollowUp_WM aInstance) {
      instance = aInstance;
    }
    
    /**
     * Creates new form RespondToFollowUp
     * @param purchaseNoID
     */
    public RespondToFollowUp_WM(String purchaseNoID) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        purchaseOrderNoField.setText(purchaseNoID);
    }
    
    public static RespondToFollowUp_WM getInstance(String purchaseNoID){
        if(instance == null)
            instance = new RespondToFollowUp_WM(purchaseNoID);
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        purchaseOrderNoLabel = new javax.swing.JLabel();
        respondToFollowUpLabel = new javax.swing.JLabel();
        purchaseOrderNoField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        shortMsgLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortMsgArea = new javax.swing.JTextArea();
        respondBtn = new javax.swing.JButton();
        wIssuesRBtn = new javax.swing.JRadioButton();
        woIssuesRBtn = new javax.swing.JRadioButton();
        incomingRBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		
		addWindowListener(new java.awt.event.WindowAdapter(){
			public void windowClosing(java.awt.event.WindowEvent evt){
				formWindowClosing(evt);
			}
		});

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        purchaseOrderNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        purchaseOrderNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        purchaseOrderNoLabel.setText("Purchase Order No.");

        respondToFollowUpLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        respondToFollowUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        respondToFollowUpLabel.setText("Respond To Follow-Up");

        shortMsgLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        shortMsgLabel.setForeground(new java.awt.Color(255, 255, 255));
        shortMsgLabel.setText("Short Message");

        shortMsgArea.setColumns(20);
        shortMsgArea.setRows(5);
        jScrollPane1.setViewportView(shortMsgArea);

        respondBtn.setBackground(new java.awt.Color(255, 255, 255));
        respondBtn.setForeground(new java.awt.Color(0, 153, 255));
        respondBtn.setText("RESPOND");
        respondBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respondBtnActionPerformed(evt);
            }
        });

        wIssuesRBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        wIssuesRBtn.setForeground(new java.awt.Color(255, 255, 255));
        wIssuesRBtn.setText("NO -  w/ issues");
        wIssuesRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wIssuesRBtnActionPerformed(evt);
            }
        });

        woIssuesRBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        woIssuesRBtn.setForeground(new java.awt.Color(255, 255, 255));
        woIssuesRBtn.setText("NO -  w/o issues");

        incomingRBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        incomingRBtn.setForeground(new java.awt.Color(255, 255, 255));
        incomingRBtn.setText("Incoming");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purchaseOrderNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purchaseOrderNoLabel)
                                    .addComponent(shortMsgLabel))
                                .addGap(136, 136, 136))
                            .addComponent(respondBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(incomingRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wIssuesRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(woIssuesRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respondToFollowUpLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(respondToFollowUpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchaseOrderNoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(purchaseOrderNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wIssuesRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(woIssuesRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incomingRBtn)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(shortMsgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respondBtn)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wIssuesRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wIssuesRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wIssuesRBtnActionPerformed

    private void respondBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respondBtnActionPerformed
        // TODO add your handling code here:
        
        String purchaseNo = getPurchaseOrderNoField().getText().trim();
        AccessLayer.getInstance().clearResponses(purchaseNo);
        String buttonChoice = "";
        
        if(wIssuesRBtn.isSelected()){
            buttonChoice = "With Issues...";
        }else if(woIssuesRBtn.isSelected()){
            buttonChoice = "Without Issues...";
        }else if(incomingRBtn.isSelected()){
            buttonChoice = "Incoming...";
        }
        
        String respondMsg = getShortMsgArea().getText().trim();
        String currDate = getCurrentDate().trim();
        String responseStats = "DONE"; // DONE <finish responding> and OK <finish reading respond> status
        
        /**
        JOptionPane.showMessageDialog(null,"Purchase No. is "+purchaseNo+" / Choice is "+buttonChoice+" / "
                + "Respond Msg. is "+respondMsg+" / Current Date is "+currDate+" "); **/
        
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to send the response?","Confirmation",0);
            if(dialogResult == JOptionPane.YES_OPTION){
                
                
                    if(new responseModel(purchaseNo, buttonChoice, respondMsg, currDate, responseStats).addResponseToDB(true)){}

                        //AccessLayer.getInstance().updateResponseStatus(purchaseNo); //if successfully sent
                        AccessLayer.getInstance().updateFollowUpFlag(purchaseNo);
                            JOptionPane.showMessageDialog(null,"Response was sent successfully!");


                    }else{

                        JOptionPane.showMessageDialog(null,"Cancelled!");
                    }
        
        // add a function here that closes the panel after user has clicked RESPOND
        // if user has responded already, user cannot respond again -  becoz only once a day
        System.gc();

    }//GEN-LAST:event_respondBtnActionPerformed

    
    public String getCurrentDate(){
        
        String myDate = "";
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try{
            myDate = dateFormat.format(date);
            
        }catch(Exception e){
            OptionPane.error("Error! Invalid in Date Format!");
        }
        
        //JOptionPane.showMessageDialog(null,"Current Date is "+myDate);
        return myDate;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespondToFollowUp_WM(purchaseNoID).setVisible(true);
            }
        });
    }
    
    
    
    private void showExitDialog(){
          //newFollowUp.instance.setEnabled(true);
          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt){
        showExitDialog();
    }
    
    /**
     * Getters and Setters
     * @return 
     */
    public JRadioButton getIncomingRBtn() {
        return incomingRBtn;
    }

    public void setIncomingRBtn(JRadioButton incomingRBtn) {
        this.incomingRBtn = incomingRBtn;
    }

    public JTextField getPurchaseOrderNoField() {
        return purchaseOrderNoField;
    }

    public void setPurchaseOrderNoField(JTextField purchaseOrderNoField) {
        this.purchaseOrderNoField = purchaseOrderNoField;
    }

    public JTextArea getShortMsgArea() {
        return shortMsgArea;
    }

    public void setShortMsgArea(JTextArea shortMsgArea) {
        this.shortMsgArea = shortMsgArea;
    }

    public JRadioButton getwIssuesRBtn() {
        return wIssuesRBtn;
    }

    public void setwIssuesRBtn(JRadioButton wIssuesRBtn) {
        this.wIssuesRBtn = wIssuesRBtn;
    }

    public JRadioButton getWoIssuesRBtn() {
        return woIssuesRBtn;
    }

    public void setWoIssuesRBtn(JRadioButton woIssuesRBtn) {
        this.woIssuesRBtn = woIssuesRBtn;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton incomingRBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField purchaseOrderNoField;
    private javax.swing.JLabel purchaseOrderNoLabel;
    private javax.swing.JButton respondBtn;
    private javax.swing.JLabel respondToFollowUpLabel;
    private javax.swing.JTextArea shortMsgArea;
    private javax.swing.JLabel shortMsgLabel;
    private javax.swing.JRadioButton wIssuesRBtn;
    private javax.swing.JRadioButton woIssuesRBtn;
    // End of variables declaration//GEN-END:variables
}
