/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package deliveryoversightsystem.warehouseMgr;

/**
 *
 * @author Aimee
 */
public class RespondToFollowUp_WM extends javax.swing.JFrame {

    /**
     * Creates new form RespondToFollowUp
     */
    public RespondToFollowUp_WM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        purchaseOrderNoLabel = new javax.swing.JLabel();
        respondToFollowUpLabel = new javax.swing.JLabel();
        purchaseOrderNoField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        shortMsgLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortMsgArea = new javax.swing.JTextArea();
        respondBtn = new javax.swing.JButton();
        wIssuesRBtn = new javax.swing.JRadioButton();
        woIssuesRBtn = new javax.swing.JRadioButton();
        incomingRBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        purchaseOrderNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        purchaseOrderNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        purchaseOrderNoLabel.setText("Purchase Order No.");

        respondToFollowUpLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        respondToFollowUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        respondToFollowUpLabel.setText("Respond To Follow-Up");

        shortMsgLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        shortMsgLabel.setForeground(new java.awt.Color(255, 255, 255));
        shortMsgLabel.setText("Short Message");

        shortMsgArea.setColumns(20);
        shortMsgArea.setRows(5);
        jScrollPane1.setViewportView(shortMsgArea);

        respondBtn.setBackground(new java.awt.Color(255, 255, 255));
        respondBtn.setForeground(new java.awt.Color(0, 153, 255));
        respondBtn.setText("RESPOND");

        wIssuesRBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        wIssuesRBtn.setForeground(new java.awt.Color(255, 255, 255));
        wIssuesRBtn.setText("NO -  w/ issues");
        wIssuesRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wIssuesRBtnActionPerformed(evt);
            }
        });

        woIssuesRBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        woIssuesRBtn.setForeground(new java.awt.Color(255, 255, 255));
        woIssuesRBtn.setText("NO -  w/o issues");

        incomingRBtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        incomingRBtn.setForeground(new java.awt.Color(255, 255, 255));
        incomingRBtn.setText("Incoming");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purchaseOrderNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purchaseOrderNoLabel)
                                    .addComponent(shortMsgLabel))
                                .addGap(136, 136, 136))
                            .addComponent(respondBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(incomingRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wIssuesRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(woIssuesRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respondToFollowUpLabel))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(respondToFollowUpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchaseOrderNoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(purchaseOrderNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wIssuesRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(woIssuesRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incomingRBtn)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(shortMsgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respondBtn)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wIssuesRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wIssuesRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wIssuesRBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespondToFollowUp_WM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespondToFollowUp_WM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton incomingRBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField purchaseOrderNoField;
    private javax.swing.JLabel purchaseOrderNoLabel;
    private javax.swing.JButton respondBtn;
    private javax.swing.JLabel respondToFollowUpLabel;
    private javax.swing.JTextArea shortMsgArea;
    private javax.swing.JLabel shortMsgLabel;
    private javax.swing.JRadioButton wIssuesRBtn;
    private javax.swing.JRadioButton woIssuesRBtn;
    // End of variables declaration//GEN-END:variables
}
